export const gpu = [
  "api.GPU",
  "api.GPUAdapter",
  "api.GPUAdapterInfo",
  "api.GPUBindGroup",
  "api.GPUBindGroupLayout",
  "api.GPUBuffer",
  "api.GPUCanvasContext",
  "api.GPUCommandBuffer",
  "api.GPUCommandEncoder",
  "api.GPUCompilationInfo",
  "api.GPUCompilationMessage",
  "api.GPUComputePassEncoder",
  "api.GPUComputePipeline",
  "api.GPUDevice",
  "api.GPUDeviceLostInfo",
  "api.GPUError",
  "api.GPUExternalTexture",
  "api.GPUInternalError",
  "api.GPUOutOfMemoryError",
  "api.GPUPipelineError",
  "api.GPUPipelineLayout",
  "api.GPUQuerySet",
  "api.GPUQueue",
  "api.GPURenderBundle",
  "api.GPURenderBundleEncoder",
  "api.GPURenderPassEncoder",
  "api.GPURenderPipeline",
  "api.GPUSampler",
  "api.GPUShaderModule",
  "api.GPUSupportedFeatures",
  "api.GPUSupportedLimits",
  "api.GPUTexture",
  "api.GPUTextureView",
  "api.GPUUncapturedErrorEvent",
  "api.GPUValidationError",
];

export const alerts = [
  "api.Window.alert",
  "api.Window.close",
  "api.Window.confirm",
  "api.Window.prompt",
];

export const storage = [
  "api.Window.localStorage",
  "api.Window.sessionStorage",
  "api.Storage",
];
